import React from "react";
import NavBar from "./NavBar";
import Footer from "./Footer";
import Image from "next/image";
import Banner from "../utils/image/agib_banner.jpg";
import Mint from "./Mint";

export default function Layout({ children }) {
  return (
    <div className="flex flex-col h-screen justify-between overflow-x-hidden overflow-y-scroll">
      <div>
        <div className="relative">
          <Image
            src={Banner}
            alt="banner image"
            width={1920}
            height={2179}
            layout="responsive"
            priority={true}
          />
          <div className="absolute top-[32%] left-[12%] w-[32%] text-xs lg:text-base xl:text-lg text-agib-blue">
            AGIB means {'"'}A Girlfriend Is Born{'"'}! AGIB is an AI-generative
            NFTs, every anime girl is unique, generated by AI. Wish you like our
            crypto girlfriend and want to be part of.
          </div>
          <NavBar />
          <Mint />
        </div>

        <div>{children}</div>
      </div>
      <Footer />
    </div>
  );
}
