import React from "react";
import NavBar from "./NavBar";
import Footer from "./Footer";
import Image from "next/image";
import Banner from "../utils/image/agib_banner.jpg";
import Mint from "./Mint";
import Story from "./Story";

export default function Layout({ children }) {
  return (
    <div className="flex flex-col h-screen justify-between overflow-x-hidden overflow-y-scroll">
      <div>
        <div className="relative">
          <div className="hidden md:block">
            <Image
              src={Banner}
              alt="banner image"
              width={1920}
              height={2179}
              layout="responsive"
              priority={true}
            />
          </div>
          <div className="pt-24 md:hidden">
            <Image
              src="/banner_mobile.png"
              alt="banner image"
              width={1184}
              height={1920}
              layout="responsive"
              priority={true}
            />
          </div>
          <div className="flex flex-col justify-between items-center absolute top-[108%] left-[12%] w-[76%] md:top-[32%] md:w-[32%]">
            <div className="text-center text-base md:text-sm md:text-left lg:text-base xl:text-lg text-agib-blue mb-8">
              AGIB means {'"'}A Girlfriend Is Born{'"'}! AGIB is an
              AI-generative NFTs, every anime girl is unique, generated by AI.
              Wish you like our crypto girlfriend and want to be part of.
            </div>
            <Mint />
          </div>

          <div className="absolute top-[75%] left-[2%] w-[95%] z-0 md:hidden">
            <Image
              src="/biglogo.png"
              alt="biglogo image"
              width={693}
              height={355}
              layout="responsive"
              priority={true}
            />
          </div>
          <Story />
          <NavBar />
        </div>

        <div>{children}</div>
      </div>
      <Footer />
    </div>
  );
}
