import React from 'react'

export default function Story() {
  return (
    <div className="absolute top-[70%] left-[20%] w-[60%] text-xs lg:text-base xl:text-lg text-white">
    AGIB means {'"'}A Girlfriend Is Born{'"'}! AGIB is an AI-generative
    NFTs, every anime girl is unique, generated by AI. Wish you like our
    crypto girlfriend and want to be part of.
    </div>
  )
}
